//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Info
    {
        public string ClassID { get; set; }
        public string ClassName { get; set; }
    }
}
