//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login_Info_ss2
    {
        public int Id { get; set; }
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage ="Điển đủ thông tin.")]
        public string UserName { get; set; }
        [DisplayName("Mật khẩu")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Điển đủ thông tin.")]
        public string Password { get; set; }
        public Nullable<int> AccessLevel { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
