//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login_Info
    {
        public int UserID { get; set; }
        [DisplayName("Tài khoản:")]
        [Required(ErrorMessage = "Vui lòng nhập hết")]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Mật khẩu:")]
        [Required(ErrorMessage = "Vui lòng nhập hết")]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
