//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ScoreCN
    {
        [DisplayName("Mã học sinh")]
        public string StudentID { get; set; }
        [DisplayName("Lớp")]
        public string ClassID { get; set; }
        [DisplayName("Họ")]
        public string LastName { get; set; }
        [DisplayName("Tên")]
        public string FirstName { get; set; }
        [DisplayName("Toán")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Toan { get; set; }
        [DisplayName("Ngữ Văn")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Van { get; set; }
        [DisplayName("Sinh học")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Sinh { get; set; }
        [DisplayName("Vật lý")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Ly { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        [DisplayName("Hóa học")]
        public Nullable<double> Hoa { get; set; }
        [DisplayName("Lịch sử")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Su { get; set; }
        [DisplayName("Địa lý")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Dia { get; set; }
        [DisplayName("Ngoại ngữ")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> NN { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> GDCD { get; set; }
        [DisplayName("Công Nghệ")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> CN { get; set; }
        [DisplayName("Tin học")]
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Tin { get; set; }
        [DisplayName("Thể dục")]
        public Nullable<bool> TD { get; set; }
        public Nullable<double> TBHK2 { get; set; }
    }
}
