//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ScoreHK1
    {
        public string StudentID { get; set; }
        public string ClassID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Toan { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Van { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Sinh { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Ly { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Hoa { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Su { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Dia { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> NN { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> GDCD { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> CN { get; set; }
        [Range(0, 10, ErrorMessage = "Vui lòng nhập lại")]
        public Nullable<double> Tin { get; set; }
        public Nullable<bool> TD { get; set; }
        public Nullable<double> TBHK1 { get; set; }
    }
}
