//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_B.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_B_FinalEntities : DbContext
    {
        public Project_B_FinalEntities()
            : base("name=Project_B_FinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class_Info> Class_Info { get; set; }
        public DbSet<ScoreCN> ScoreCNs { get; set; }
        public DbSet<ScoreHK1> ScoreHK1 { get; set; }
    }
}
